<?php

namespace Jose\AiVisibility\Model;

use Magento\Catalog\Model\ResourceModel\Product\CollectionFactory as ProductCollectionFactory;
use Magento\Catalog\Model\ResourceModel\Category\CollectionFactory as CategoryCollectionFactory;
use Magento\CatalogInventory\Model\ResourceModel\Stock\Status as StockStatus;
use Magento\Cms\Api\PageRepositoryInterface;
use Magento\Framework\Api\SearchCriteriaBuilder;
use Magento\Framework\Exception\NoSuchEntityException;
use Magento\Framework\UrlInterface;
use Magento\Store\Model\StoreManagerInterface;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Store\Model\ScopeInterface;

class LlmsTxtGenerator
{
    private ProductCollectionFactory $productCollectionFactory;
    private CategoryCollectionFactory $categoryCollectionFactory;
    private PageRepositoryInterface $pageRepository;
    private SearchCriteriaBuilder $searchCriteriaBuilder;
    private StockStatus $stockStatus;
    private StoreManagerInterface $storeManager;
    private ScopeConfigInterface $scopeConfig;

    public function __construct(
        ProductCollectionFactory $productCollectionFactory,
        CategoryCollectionFactory $categoryCollectionFactory,
        PageRepositoryInterface $pageRepository,
        SearchCriteriaBuilder $searchCriteriaBuilder,
        StockStatus $stockStatus,
        StoreManagerInterface $storeManager,
        ScopeConfigInterface $scopeConfig
    ) {
        $this->productCollectionFactory = $productCollectionFactory;
        $this->categoryCollectionFactory = $categoryCollectionFactory;
        $this->pageRepository = $pageRepository;
        $this->searchCriteriaBuilder = $searchCriteriaBuilder;
        $this->stockStatus = $stockStatus;
        $this->storeManager = $storeManager;
        $this->scopeConfig = $scopeConfig;
    }

    /**
     * Generate the llms.txt content for a store.
     *
     * @param int|null $storeId
     * @return string
     * @throws NoSuchEntityException
     */
    public function generate(?int $storeId = null): string
    {
        $storeId = $storeId ?? (int) $this->storeManager->getStore()->getId();
        $store   = $this->storeManager->getStore($storeId);
        $baseUrl = $store->getBaseUrl(UrlInterface::URL_TYPE_LINK);

        $maxProducts   = (int) $this->getConfig('max_products', $storeId);
        $maxCategories = (int) $this->getConfig('max_categories', $storeId);
        $maxCmsPages   = (int) $this->getConfig('max_cms_pages', $storeId);
        $includeOOS    = (bool) $this->getConfig('include_out_of_stock', $storeId);

        $lines   = [];
        $lines[] = "# {$store->getName()}";
        $lines[] = '';
        $lines[] = "> {$baseUrl} — E-commerce store with "
            . $this->getTotalProductCount($storeId)
            . " products across "
            . $this->getTotalCategoryCount($storeId)
            . " categories.";
        $lines[] = '';

        // --- Categories ---
        $lines[] = '## Categories';
        $lines[] = '';
        foreach ($this->getCategories($storeId, $maxCategories) as $category) {
            $lines[] = "- [{$category->getName()}]({$category->getUrl()})";
        }
        $lines[] = '';

        // --- Products ---
        $lines[] = '## Products';
        $lines[] = '';
        foreach ($this->getProducts($storeId, $maxProducts, $includeOOS) as $product) {
            $price = $this->formatPrice((float) $product->getFinalPrice(), $store);
            $line  = "- [{$product->getName()}]({$product->getProductUrl()})";
            if ($price) {
                $line .= " — {$price}";
            }
            $lines[] = $line;
        }
        $lines[] = '';

        // --- CMS Pages ---
        $cmsPages = $this->getCmsPages($maxCmsPages);
        if (!empty($cmsPages)) {
            $lines[] = '## Pages';
            $lines[] = '';
            foreach ($cmsPages as $page) {
                if (!$page->isActive() || !$page->isPublished()) {
                    continue;
                }
                $lines[] = "- [{$page->getTitle()}]({$baseUrl}{$page->getIdentifier()})";
            }
            $lines[] = '';
        }

        // --- Footer ---
        $lines[] = '---';
        $lines[] = 'Last updated: ' . date('Y-m-d H:i:s');
        $lines[] = 'Generated by Jose_AiVisibility';

        return implode("\n", $lines);
    }

    /**
     * @param int $storeId
     * @param int $limit
     * @param bool $includeOOS
     * @return array
     */
    private function getProducts(int $storeId, int $limit, bool $includeOOS): array
    {
        $collection = $this->productCollectionFactory->create()
            ->addAttributeToSelect(['name', 'price', 'final_price', 'url_key'])
            ->addFieldToFilter('visibility', ['in' => [2, 3, 4]])
            ->addFieldToFilter('status', 1)
            ->addUrlRewrite()
            ->setStoreId($storeId)
            ->setPageSize($limit)
            ->setCurPage(1)
            ->setOrder('entity_id', 'DESC');

        if (!$includeOOS) {
            $this->stockStatus->addIsInStockFilterToCollection($collection);
        }

        return $collection->getItems();
    }

    /**
     * @param int $storeId
     * @param int $limit
     * @return array
     */
    private function getCategories(int $storeId, int $limit): array
    {
        return $this->categoryCollectionFactory->create()
            ->setStoreId($storeId)
            ->addAttributeToSelect(['name', 'url_key'])
            ->addAttributeToFilter('is_active', 1)
            ->addAttributeToFilter('parent_id', ['gt' => 1])
            ->setPageSize($limit)
            ->setCurPage(1)
            ->setOrder('name', 'ASC')
            ->getItems();
    }

    /**
     * @param int $limit
     * @return array
     */
    private function getCmsPages(int $limit): array
    {
        $searchCriteria = $this->searchCriteriaBuilder
            ->addFilter('is_active', 1)
            ->setPageSize($limit)
            ->create();

        return $this->pageRepository->getList($searchCriteria)->getItems();
    }

    /**
     * @param int $storeId
     * @return int
     */
    private function getTotalProductCount(int $storeId): int
    {
        return (int) $this->productCollectionFactory->create()
            ->setStoreId($storeId)
            ->addFieldToFilter('status', 1)
            ->getSize();
    }

    /**
     * @param int $storeId
     * @return int
     */
    private function getTotalCategoryCount(int $storeId): int
    {
        return (int) $this->categoryCollectionFactory->create()
            ->setStoreId($storeId)
            ->addAttributeToFilter('is_active', 1)
            ->getSize();
    }

    /**
     * @param float $price
     * @param \Magento\Store\Api\Data\StoreInterface $store
     * @return string|null
     */
    private function formatPrice(float $price, $store): ?string
    {
        if ($price <= 0) {
            return null;
        }

        return $store->getCurrentCurrency()->format($price, [], true);
    }

    /**
     * @param string $key
     * @param int $storeId
     * @return mixed
     */
    private function getConfig(string $key, int $storeId): mixed
    {
        return $this->scopeConfig->getValue(
            "ai_visibility/llms_txt/{$key}",
            ScopeInterface::SCOPE_STORE,
            $storeId
        );
    }
}
