<?php

namespace Jose\AiVisibility\Model;

use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Store\Model\ScopeInterface;

class RobotsTxtGenerator
{
    private const AI_BOTS = [
        'oai_searchbot'     => 'OAI-SearchBot',
        'gptbot'            => 'GPTBot',
        'chatgpt_user'      => 'ChatGPT-User',
        'claude_searchbot'  => 'Claude-SearchBot',
        'claude_user'       => 'Claude-User',
        'perplexitybot'     => 'PerplexityBot',
        'perplexity_user'   => 'Perplexity-User',
        'google_extended'   => 'Google-Extended',
        'anthropic_ai'      => 'anthropic-ai',
        'applebot_extended' => 'Applebot-Extended',
    ];

    private ScopeConfigInterface $scopeConfig;

    public function __construct(
        ScopeConfigInterface $scopeConfig
    ) {
        $this->scopeConfig = $scopeConfig;
    }

    /**
     * Build the "User-agent / Allow" rules for the AI bots.
     *
     * @return string
     */
    public function generateAiRules(): string
    {
        if (!$this->isEnabled()) {
            return '';
        }

        $lines   = [];
        $lines[] = '# ============================================================';
        $lines[] = '# AI SEARCH & INDEXING BOTS — Generated by Jose_AiVisibility';
        $lines[] = '# ============================================================';

        foreach (self::AI_BOTS as $configKey => $botName) {
            $configPath = "ai_visibility/robots/allow_{$configKey}";
            if ($this->scopeConfig->isSetFlag($configPath, ScopeInterface::SCOPE_STORE)) {
                $lines[] = "User-agent: {$botName}";
                $lines[] = 'Allow: /';
                $lines[] = '';
            }
        }

        $lines[] = '# ============================================================';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * @return bool
     */
    private function isEnabled(): bool
    {
        return $this->scopeConfig->isSetFlag(
            'ai_visibility/robots/enable',
            ScopeInterface::SCOPE_STORE
        );
    }
}
